import { Card, Suit, Rank, Season } from './types.js';

const SUIT_SEASON: Record<Suit, Season> = {
  hearts: 'spring',
  diamonds: 'summer',
  clubs: 'autumn',
  spades: 'winter',
};

function card(suit: Suit, rank: Rank, promptA: string, promptB: string | null, specialRules: string | null = null): Card {
  return {
    id: `${suit}-${rank}`,
    suit,
    rank,
    season: SUIT_SEASON[suit],
    promptA,
    promptB,
    specialRules,
  };
}

// ============ SPRING (Hearts) ============
const springCards: Card[] = [
  card('hearts', 'ace',
    'What is the highest-status group in the community? What gives them this status? What must people do to be accepted into this group?',
    'Are there distinct family units in the community? If so, what structures do they take? If not, what takes the place of the family?'),
  card('hearts', '2',
    'There is a large body of water on the map. Where is it? What does it look like?',
    'There is a giant, man-made structure on the map. Where is it? Why was it abandoned?'),
  card('hearts', '3',
    'Someone new arrives. Who are they? Why are they in distress?',
    'Two of the community\'s younger members get into a fight. What provoked them?'),
  card('hearts', '4',
    'What important tools or basic implements does the community lack?',
    'Where does everyone sleep? Who is unhappy with the current arrangement, and why?'),
  card('hearts', '5',
    'There\'s a disquieting legend about this area. What is it?',
    'A broken piece of machinery is discovered. What is it? What could it be used for?'),
  card('hearts', '6',
    'What role do children play in the community?',
    'Where is food stored? Create a location to show this. How reliable is it?'),
  card('hearts', '7',
    'Alarming weather destroys something. What weather? What does it destroy?',
    'A charismatic young girl convinces many people to help her with a project. What is it? Start a project.'),
  card('hearts', '8',
    'What are the community\'s eldest members like? What special needs do they have?',
    'A charismatic young girl tempts many people into sinful activity. What is it?'),
  card('hearts', '9',
    'Are there natural predators in the area? Are they a threat?',
    'Start a project to build or create something beautiful, or to demolish something hideous.'),
  card('hearts', '10',
    'Introduce another community on the map. What sets them apart from yours?',
    'Is there a belief or practice that unifies your community?'),
  card('hearts', 'jack',
    'You see a good omen. What is it?',
    'You see a bad omen. What is it?'),
  card('hearts', 'queen',
    'What is the most beautiful thing in this area?',
    'What is the most hideous thing in this area?'),
  card('hearts', 'king',
    'A young boy digs in the ground and finds something unexpected. What is it?',
    'An old man confesses to past atrocities. What are they?'),
];

// ============ SUMMER (Diamonds) ============
const summerCards: Card[] = [
  card('diamonds', 'ace',
    'A contingent within the community demands to be heard. Who are they? What are they insisting?',
    'A contingent within the community has been damaged or wronged by the outside. What are they upset about? How do they respond?'),
  card('diamonds', '2',
    'Someone new arrives in a state of distress. Who are they? What has happened to them?',
    'Someone leaves the community. Who? What are they looking for?'),
  card('diamonds', '3',
    'Start a project related to food production or gathering.',
    'Start a project related to defense or military readiness.'),
  card('diamonds', '4',
    'The eldest among you dies. What was their final wish?',
    'The eldest among you is very sick. Do not reduce project dice this week.',
    'Option B: Do not reduce project dice this week.'),
  card('diamonds', '5',
    'A project finishes early. Which one? Why?',
    'The weather is nice and people throw themselves into their work. Start a new project.',
    'Option A: Choose a project to complete immediately.'),
  card('diamonds', '6',
    'Outsiders arrive in the area. How many? What is their most obvious threat or vulnerability?',
    'Outsiders arrive in the area. How many? How are they greeted?'),
  card('diamonds', '7',
    'Introduce a mystery at the edge of the map.',
    'An unattended situation becomes more complicated or scary. What happens?'),
  card('diamonds', '8',
    'Someone tries to seize control of the community by force. Do they succeed? Why do they do this?',
    'A community member starts a foolish project. What is it? Start a project.'),
  card('diamonds', '9',
    'A project fails. Which one? Why?',
    'Something goes foul and supplies are lost. Add a new Scarcity.',
    'Option A: Choose a project to fail.'),
  card('diamonds', '10',
    'You discover a cache of supplies in a forgotten place. Add a new Abundance.',
    'Start a project related to an existing Scarcity.'),
  card('diamonds', 'jack',
    'Predators or a bad omen cause someone to go missing. Who?',
    'Predators or a bad omen lead to a change. What measures do you take? Do not reduce project dice this week.',
    'Option B: Do not reduce project dice this week.'),
  card('diamonds', 'queen',
    'A project finishes early. Which one? Why?',
    'Boredom leads to a fight between two people. What is the fight about? Do others get involved?',
    'Option A: Choose a project to complete immediately.'),
  card('diamonds', 'king',
    'Summer is fleeting. Discard the top 2 cards from the deck and take two actions this turn instead of one.',
    null,
    'Discard top 2 cards. Take two actions this turn.'),
];

// ============ AUTUMN (Clubs) ============
const autumnCards: Card[] = [
  card('clubs', 'ace',
    'The community becomes obsessed with one of its projects. Add 3 weeks to that project, or if you prefer, all other projects fail.',
    'The community becomes obsessed with a single vision for the future. Hold an extra discussion about what it is.',
    'Option A: Add 3 weeks to a project OR all other projects fail.'),
  card('clubs', '2',
    'Someone returns to the community who left under dark circumstances. Who? Where did they go?',
    'You find a body. Do you recognize them? What happened?'),
  card('clubs', '3',
    'Someone leaves the community after giving a dire warning. Who? What is the warning?',
    'A dire warning is given. Start a contentious project based on it.'),
  card('clubs', '4',
    'The strongest among you dies. What happened?',
    'The weakest among you dies. Who is to blame?'),
  card('clubs', '5',
    'The Parish arrives. Who are they? Why have they come?',
    'Marauders are nearby. How many are there? What weapons do they carry?'),
  card('clubs', '6',
    'Introduce a dark mystery among the community members.',
    'Tensions flare between members. A project fails as a result.'),
  card('clubs', '7',
    'A project is not working as expected. Choose a project and radically change its nature.',
    'Something goes foul and supplies are lost. Add a new Scarcity.'),
  card('clubs', '8',
    'Someone sabotages a project, destroying it completely. Which project? Why?',
    'Someone is caught trying to sabotage a project. How does the community respond?'),
  card('clubs', '9',
    'A project finishes early due to a burst of frantic, desperate energy. Which one?',
    'Your community finds something while exploring the area that was overlooked before. What is it?',
    'Option A: Choose a project to complete immediately.'),
  card('clubs', '10',
    'The harvest is plentiful. Add an Abundance.',
    'Cold winds drive out an enemy or threat. Remove a threat from the map.'),
  card('clubs', 'jack',
    'A project finishes early. Which one? Why?',
    'Restlessness and frustration lead to violence. Who is hurt? How?',
    'Option A: Choose a project to complete immediately.'),
  card('clubs', 'queen',
    'A disease spreads through the community. You can either quarantine the sick (do not reduce project dice this week and next) or ignore it (add a Scarcity: Health or Fertility).',
    null,
    'Choose: Quarantine (no project dice reduction for 2 weeks) OR add Health/Fertility Scarcity.'),
  card('clubs', 'king',
    'A natural disaster strikes the area. You can either focus on safety (a project fails and you lose an Abundance) or protect your supplies (people die).',
    null,
    'Choose: Safety (project fails + lose Abundance) OR protect supplies (people die).'),
];

// ============ WINTER (Spades) ============
const winterCards: Card[] = [
  card('spades', 'ace',
    'The community decides to conserve energy. A project fails, but you gain an Abundance.',
    'The community pushes through with hurried labor. A project finishes early, but you gain a new Scarcity.',
    'Option A: Project fails + gain Abundance. Option B: Project finishes early + gain Scarcity.'),
  card('spades', '2',
    'A headstrong community member takes charge of a project. It fails, but another finishes early.',
    'A headstrong community member tries to take control of the community. There is a conflict. Do not reduce project dice this week.',
    'Option A: One project fails, another finishes early. Option B: No dice reduction.'),
  card('spades', '3',
    'Someone has a plan to ensure safety through the winter. Start a project related to it.',
    'An ingenious solution to a problem is discovered. A project finishes early.'),
  card('spades', '4',
    'All the children and animals in the community won\'t stop crying. Hold an extra discussion about why.',
    'Winter destroys a food source. If this creates a new Scarcity, add it.'),
  card('spades', '5',
    'A great atrocity is revealed. What is it?',
    'Winter leaves everyone cold and despondent. Do not reduce project dice this week.',
    'Option B: Do not reduce project dice this week.'),
  card('spades', '6',
    'The community decides to consolidate. Projects on the edge of the map fail. All other projects have their dice reduced by 2 extra this week.',
    'A discovery is made on the very edge of the map. Start a project related to it.'),
  card('spades', '7',
    'What is winter like in this area? How does it affect the community\'s morale?',
    null),
  card('spades', '8',
    'Desperation leads to a dark action. You can either spend the week calming things down (your turn ends with no action) or declare war on someone or something (start a project).',
    null,
    'Choose: Calm down (no action this turn) OR declare war (start a project).'),
  card('spades', '9',
    'Someone goes missing in the cold. You can either send out search parties (do not reduce project dice this week) or let them be lost forever.',
    null,
    'Choose: Search (no dice reduction) OR never seen again.'),
  card('spades', '10',
    'A huge undertaking is proposed. Start a project with a duration of at least 5 weeks.',
    null,
    'Project must have 5+ weeks duration.'),
  card('spades', 'jack',
    'An infected outsider appears at your border, carrying valuable resources. Welcome them (remove a Scarcity but risk infection) or bar entry.',
    null,
    'Choose: Welcome (remove Scarcity + risk) OR bar entry.'),
  card('spades', 'queen',
    'You see a good omen. What is it?',
    null),
  card('spades', 'king',
    'The Frost Shepherds arrive. The game is over.',
    null,
    'THE GAME ENDS IMMEDIATELY.'),
];

export const ALL_CARDS: Card[] = [
  ...springCards,
  ...summerCards,
  ...autumnCards,
  ...winterCards,
];

export function getCardsBySuit(suit: Suit): Card[] {
  return ALL_CARDS.filter(c => c.suit === suit);
}
